# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# format = '$all'
# https://starship.rs/config/#default-prompt-format
# see also video: https://youtu.be/VgTu1_92U0U?list=PL_L_J_Lv0U2oekcBcc-Ptm7ML4BxoCqdT&t=269
#
# format = """
# $directory"""

[username]
show_always = true

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                                    # The name of the module we are configuring is "character"
success_symbol = '[ï²](bold green)'    # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = '[âœ—](bold red) '

[cmd_duration]
min_time = 100
format = 'underwent [$duration](bold yellow)'

[battery]
full_symbol = "â€¢ "
charging_symbol = "â‡¡ "
discharging_symbol = "â‡£ "
unknown_symbol = "â“ "
empty_symbol = "â— "

[c]
symbol = "î˜ "

[directory]
read_only = " ï ½"

[docker_context]
symbol = "ïŒˆ "

[git_branch]
symbol = "ï˜ "

[golang]
symbol = "î˜§ "

[memory_usage]
symbol = "ï¡š "

[nodejs]
symbol = "[â¬¢](bold green) "

[rust]
symbol = "î¨ "

[pulumi]
symbol = "ğŸ§Š "

[typst]
symbol = "t "
